spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 172.1.38.177:3306/meokjang?serverTimezone=UTC&characterEncoding=UTF-8
    username: meokjangadmin
    password: qwe1234@

  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
      hibernate.format_sql: true
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  logging.level:
    org.hibernate.SQL: debug

DOCUMENT_URL: https://wz5hxm22cp.apigw.ntruss.com/custom/v1/22356/c5b21f287dfdfcf5d994a88e97fbecca2598ae86c8ab8715da1502276d33dfbd/document/receipt
GENERAL_URL: https://zw5r96cs6p.apigw.ntruss.com/custom/v1/22222/922b6af23c184d97e9f5ac8ff6bd23af51060c57d6383df4457343e13618a68d/general
DOCUMENT_SECRET_KEY: aVN6V3p0VE9DbWRoWXpHSXVCRHZKQWFwWXJKY1pMdEM=
GENERAL_SECRET_KEY: UEVlcUdWSktRZXlObkNYdkhNbm5vaFdBaVdkdnd6TWE=