name: CI_CD
run-name: CI_CD workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Qemu
        uses: docker/setup-qemu-action@v2

      - name: Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ACCESS_KEY }}
          password: ${{ secrets.ACCESS_SECRET_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create application.yml
        run: touch ./src/main/resources/application.yml

      - name: Create config
        run: touch ./src/main/resources/config

      - name: Create oci_api_key.pem
        run: touch ./src/main/resources/oci_api_key.pem

      - name: Set up application.yml
        run: echo "${{ secrets.APPLICATION_YAML_CONTENT }}" > ./src/main/resources/application.yml

      - name: Set up config
        run: echo "${{ secrets.CONFIG_CONTENT }}" > ./src/main/resources/config

      - name: Set up oci_api_key.pem
        run: echo "${{ secrets.OCI_API_KEY_CONTENT }}" > ./src/main/resources/oci_api_key.pem

      - name: Upload application.yml
        uses: actions/upload-artifact@v2
        with:
          name: application.yml
          path: ./src/main/resources/application.yml

      - name: Upload config
        uses: actions/upload-artifact@v2
        with:
          name: config
          path: ./src/main/resources/config

      - name: Upload oci_api_key.pem
        uses: actions/upload-artifact@v2
        with:
          name: oci_api_key.pem
          path: ./src/main/resources/oci_api_key.pem

      - name: Set ENV
        run: echo "TIME=$(date "+%Y-%m-%d-%H-%M")" >> $GITHUB_ENV

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: dlrkdals909/meokjang:${{ env.TIME }}