name: CI_CD
run-name: CI_CD workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Qemu
        uses: docker/setup-qemu-action@v2

      - name: Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ACCESS_KEY }}
          password: ${{ secrets.ACCESS_SECRET_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create resource directory
        run: mkdir -p ./src/main/resources

      - name: Set up application.yml
        run: echo "${{ secrets.APPLICATION_YAML_CONTENT }}" > ./src/main/resources/application.yml

      - name: Set up config
        run: echo "${{ secrets.CONFIG_CONTENT }}" > ./src/main/resources/config

      - name: Set up oci_api_key.pem
        run: echo "${{ secrets.OCI_API_KEY_CONTENT }}" > ./src/main/resources/oci_api_key.pem

      - name: Set up firebase-adminsdk.json
        run: echo "${{ secrets.FIREBASE_ADMINSDK_CONTENT }}" > ./src/main/resources/firebase-adminsdk.json

      - name: Set ENV
        run: echo "TIME=$(date "+%Y-%m-%d-%H-%M")" >> $GITHUB_ENV

      - name: Build and Push
        run: |
          docker build -t dlrkdals909/meokjang:${{ env.TIME }} .
          docker push dlrkdals909/meokjang:${{ env.TIME }}
