name: CI_CD
run-name: CI_CD workflow
on:
  push:
  pull_request:
    types: [merged]

jobs:
  deploy-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Qemu
        uses: docker/setup-qemu-action@v2

      - name: Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ACCESS_KEY }}
          password: ${{ secrets.ACCESS_SECRET_KEY }}

      - name: Set ENV
        run: echo "TIME=$(date "+%Y-%m-%d-%H-%M")" >> $GITHUB_ENV

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: dlrkdals909/meokjang:${{ env.TIME }}
