name: CI_CD
run-name: CI_CD workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Qemu
        uses: docker/setup-qemu-action@v2

      - name: Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ACCESS_KEY }}
          password: ${{ secrets.ACCESS_SECRET_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create resources directory
        run: mkdir -p ./src/main/resources

      - name: Set up application.yml
        env:
          APPLICATION_YAML_CONTENT: ${{ secrets.APPLICATION_YAML_CONTENT }}
        run: echo $APPLICATION_YAML_CONTENT | base64 —decode > ./src/main/resources/application.yml

      - name: Set ENV
        run: echo "TIME=$(date "+%Y-%m-%d-%H-%M")" >> $GITHUB_ENV

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: dlrkdals909/meokjang:${{ env.TIME }}